apiVersion: v1
kind: ConfigMap
metadata:
  name: neom2-wallet-config
data:
  issuer-config.json: |
    {
      "issuerUiUrl": "https://howest.neom.walt-test.cloud",
      "issuerApiUrl": "https://howest.neom.walt-test.cloud/issuer-api/default",
      "issuerClientName": "walt.id howest Portal",
      "wallets": {
        "waltid": {
          "id": "waltid",
          "url": "https://eudi-wallet.neom.walt-test.cloud",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "walt.id web wallet"
        }
      }
    }
  verifier-config.json: |
    {
      "verifierUiUrl": "https://verifier.neom.walt-test.cloud",
      "verifierApiUrl": "https://verifier.neom.walt-test.cloud/verifier-api/default",
      "wallets": {
        "waltid": {
          "id": "waltid",
          "url": "https://eudi-wallet.neom.walt-test.cloud",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "walt.id web wallet"
        }
      },
      "allowedWebhookHosts": [ "https://integrations.neom.walt-test.cloud/callback/" ]
    }
  wallet-config.json: |
    {
      "walletUiUrl": "https://eudi-wallet.neom.walt-test.cloud",
      "walletApiUrl": "https://eudi-wallet.neom.walt-test.cloud/api",
      "issuers": {
        "waltid": {
          "id": "waltid",
          "url": "https://howest.neom.walt-test.cloud/issuer-api/default/oidc",
          "description": "walt.id howest Portal"
        },
        "onboarding@walt.id": {
          "id": "onboarding@walt.id",
          "url": "https://howest.neom.walt-test.cloud/onboarding-api/oidc",
          "description": "walt.id On-Boarding service"
        }
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neom2-wallet-data-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: neom2-walletkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neom2-walletkit
  template:
    metadata:
      labels:
        app: neom2-walletkit
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      containers:
        - name: neom2-walletkit
          image: waltid/walletkit:latest
          volumeMounts:
            - name: neom2-wallet-config
              mountPath: "/waltid/wallet/config/"
              readOnly: true
            - mountPath: "/waltid/wallet/data/"
              name: neom2-wallet-data
          env:
            - name: WALTID_DATA_ROOT
              value: "/waltid/wallet"
            - name: WALTID_WALLET_BACKEND_BIND_ADDRESS
              value: 0.0.0.0
            - name: WALTID_WALLET_AUTH_SECRET
              value: 0b218176-d8f3-4a58-83db-fd328defc30f
          args:
            - run
          ports:
            - containerPort: 8080
              name: http-api
      volumes:
        - name: neom2-wallet-config
          configMap:
            name: neom2-wallet-config
        - name: issuers-secret
          secret:
            secretName: issuers-secret
        - name: neom2-wallet-data
          persistentVolumeClaim:
            claimName: neom2-wallet-data-volume-claim
---
kind: Service
apiVersion: v1
metadata:
  name: neom2-walletkit
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: neom2-walletkit
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-wallet-eudi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-wallet-eudi
  template:
    metadata:
      labels:
        app: web-wallet-eudi
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      containers:
        - name: ssikit-web-wallet
          image: waltid/ssikit-web-wallet:1.2304271229.neom-eudi  # neom-eudi
          ports:
            - containerPort: 80
              name: http-api
---
kind: Service
apiVersion: v1
metadata:
  name: web-wallet-eudi
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: web-wallet-eudi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: howest-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: howest-portal
  template:
    metadata:
      labels:
        app: howest-portal
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      containers:
        - name: howest-portal
          image: waltid/ssikit-issuer-portal:1.2304190916.neom-howest
          ports:
            - containerPort: 80
              name: http-api
---
kind: Service
apiVersion: v1
metadata:
  name: howest-portal
spec:
  ports:
    - name: http
      port: 80
      targetPort: http-api
      protocol: TCP
  selector:
    app: howest-portal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neom2-walletkit
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/configuration-snippet: |
      if ($host ~ ^(.+)\.waltid\.org$) {
        return 301 https://$1.neom.walt-test.cloud$request_uri;
      }
spec:
  tls:
    - hosts:
        - eudi-wallet.neom.walt-test.cloud
        - howest.neom.walt-test.cloud
      secretName: wallet-tls-secret
  rules:
    - host: eudi-wallet.neom.walt-test.cloud
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /verifier-api/
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /issuer-api/
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /onboarding-api/
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /webjars
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /v2/nftkit/nft/
            pathType: Prefix
            backend:
              service:
                name: nftkit
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-wallet-eudi
                port:
                  number: 80
    - host: howest.neom.walt-test.cloud
      http:
        paths:
          - path: /issuer-api/
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /onboarding-api/
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: neom2-walletkit
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: howest-portal
                port:
                  number: 80
