version: "3.3"
services:
  wallet-backend:
    image: waltid/ssikit-wallet-backend:latest
    volumes:
      - ./verifier-config.json:/Webwallet-Backend/verifier-config.json
      - ./issuer-config.json:/Webwallet-Backend/issuer-config.json
      - ../data:/Webwallet-Backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  wallet-ui:
    image: waltid/ssikit-web-wallet:latest
  verifier-ui:
    image: waltid/ssikit-verifier-portal:latest
  issuer-ui:
    image: waltid/ssikit-issuer-portal:latest
  ingress:
    image: nginx:1.15.10-alpine
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
      - target: 81
        published: 8081
        protocol: tcp
        mode: host
      - target: 82
        published: 8082
        protocol: tcp
        mode: host
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf