name: Snapshot release workflow for Walt.ID Wallet Kit

on:
  push:
    tags:
      - 'v*'

jobs:
  verify-wrapper:
    name: "Verification"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

  gradle:
    needs: verify-wrapper
    name: "Build"
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Build and Push SNAPSHOT
        uses: philpotisk/github-action-docker-build-push@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_FILE: Dockerfile
          CONTAINER_TAG: ${{ format('waltid/walletkit:{0}', github.ref_name) }}
      - name: Prepare CD
        run: sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g; s/_VERSION_TAG_/$GITHUB_REF_NAME/g" k8s/deployment-prod.yaml > k8s/deployment_mod.yaml
      - name: Continuous deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n default -f k8s/deployment_mod.yaml
